# `README.md`, assembled from the directories that have something to say.
#
# A README for a program with four directories is four people's prose in
# one file, and the file is where it goes stale: the server's section is
# edited beside the server's nix, or it is not edited. So each directory
# writes its own in a `readme.nix` — `readme.sections.server.text` — and
# this puts them in order under the intro. The result is a generated file
# like `eas.json`: `nix run .#write-files` writes it, `nix flake check`
# fails while the committed copy differs.
{ lib, flake-parts-lib, ... }: {
  options.perSystem = flake-parts-lib.mkPerSystemOption {
    options.readme = {
      intro = lib.mkOption {
        type = lib.types.lines;
        default = "";
        description = "The top of README.md: the title, and what the program is.";
      };
      sections = lib.mkOption {
        default = { };
        description = "The rest, one per directory that has something to say, in `order`.";
        type = lib.types.attrsOf (lib.types.submodule {
          options = {
            order = lib.mkOption {
              type = lib.types.int;
              default = 50;
              description = "Where it goes. Lower is earlier; ties are alphabetical.";
            };
            text = lib.mkOption {
              type = lib.types.lines;
              description = "The section, headings included.";
            };
          };
        });
      };
    };
  };

  config.perSystem = { config, lib, ... }:
    let
      cfg = config.readme;
      sorted = lib.sort
        (a: b: a.value.order < b.value.order
          || (a.value.order == b.value.order && a.name < b.name))
        (lib.attrsToList cfg.sections);
      body = lib.concatMapStringsSep "\n\n" (s: lib.removeSuffix "\n" s.value.text) sorted;
    in
    {
      files.file."README.md" = lib.mkIf (cfg.intro != "" || cfg.sections != { }) {
        text = ''
          <!-- Generated by `nix run .#write-files` from the `readme.nix` beside each
               directory's nix. Edit those; this file is checked against them. -->
        '' + lib.optionalString (cfg.intro != "") ("\n" + lib.removeSuffix "\n" cfg.intro + "\n")
        + lib.optionalString (sorted != [ ]) ("\n" + body + "\n");
      };
    };
}
