//! Wire types. Six for the log, two for the realtime channel beside it;
//! resume and initial sync are the same path.
//!
//! Payloads are CBOR. See `docs/decisions.md` for the compatibility rules that
//! keep a log written today readable by a client built in five years.

use serde::{de::DeserializeOwned, Deserialize, Serialize};

use crate::{Error, Id, Result};

/// A position in the server's totally ordered log. The first entry is 1.
pub type Seq = u64;

/// Who authored a mutation. Opaque to Petros; the app decides what it means.
#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct ActorId(String);

impl ActorId {
    pub fn new(id: impl Into<String>) -> Self {
        ActorId(id.into())
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl From<&str> for ActorId {
    fn from(s: &str) -> Self {
        ActorId(s.to_string())
    }
}

impl From<String> for ActorId {
    fn from(s: String) -> Self {
        ActorId(s)
    }
}

impl std::fmt::Display for ActorId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

impl std::fmt::Debug for ActorId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "ActorId({:?})", self.0)
    }
}

/// One mutation, with the identity the log is deduped by.
///
/// `id` is generated by the originating client. The server dedupes on it, which
/// is what makes retrying a push whose response was lost safe without any
/// reasoning at the call site. `seq` is unset until the server assigns one.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Entry<M> {
    pub id: Id,
    pub actor: ActorId,
    #[serde(default)]
    pub seq: Option<Seq>,
    #[serde(rename = "m")]
    pub mutation: M,
    /// The login this was authored under, which `apply` sees as
    /// `ctx.session.id`. Absent for a peer that never signed in, and for an
    /// entry written before there were sessions — and absent from the bytes
    /// too, so the encoding of every entry that has none is unchanged.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session: Option<String>,
}

impl<M> Entry<M> {
    /// A new, unsequenced entry.
    pub fn new(id: Id, actor: ActorId, mutation: M) -> Self {
        Entry {
            id,
            actor,
            seq: None,
            mutation,
            session: None,
        }
    }

    /// What `apply` sees of this entry beyond its arguments.
    pub fn ctx(&self) -> petros_schema::Ctx {
        petros_schema::Ctx::new(self.actor.as_str(), self.session.as_deref().unwrap_or(""))
    }

    /// The assigned sequence number, or an error if the entry is unsequenced.
    pub fn require_seq(&self) -> Result<Seq> {
        self.seq.ok_or(Error::MissingSeq(self.id))
    }
}

/// Client to server.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "t")]
pub enum ClientMsg<M> {
    /// "I have everything up to `since`; catch me up." Sent on every connect,
    /// whether this is the first sync or the thousandth resume.
    ///
    /// `token` is what the client was given when it signed in. A server that
    /// authenticates answers a missing or stale one with [`ServerMsg::Denied`]
    /// and nothing else; one that does not never reads it.
    Hello {
        since: Seq,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        token: Option<String>,
    },
    /// Entries authored here, `seq` unset, `id` set.
    Push { entries: Vec<Entry<M>> },
    /// One frame on the realtime channel: CBOR of the app's own `Say`.
    ///
    /// Opaque here on purpose. Nothing ever replays a live frame, so the
    /// compatibility rules that bind every field above — never rename, never
    /// retype, add with `serde(default)` — do not bind what is inside this
    /// one, and an app is free to change its realtime protocol as often as it
    /// ships its clients. See [`crate::live`].
    Say { say: Vec<u8> },
}

/// Server to client.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "t")]
pub enum ServerMsg<M> {
    /// Confirmed entries, in log order. `has_more` means send another `Hello`.
    Batch {
        entries: Vec<Entry<M>>,
        has_more: bool,
    },
    /// These pushed entries are in the log at these sequence numbers.
    /// Parallel arrays: `ids[i]` was assigned `seqs[i]`.
    Ack { ids: Vec<Id>, seqs: Vec<Seq> },
    /// This pushed entry will never be in the log.
    Reject { id: Id, reason: String },
    /// This connection is not signed in, or not as who it claims. Nothing
    /// else will be sent on it; the client has to sign in again and
    /// reconnect. A verdict about the connection, not about any entry — the
    /// pending mutations are kept and re-offered next time.
    Denied { reason: String },
    /// One frame on the realtime channel: CBOR of the app's own `Hear`.
    Heard { hear: Vec<u8> },
}

/// Encode a value as CBOR.
pub fn encode<T: Serialize>(value: &T) -> Result<Vec<u8>> {
    let mut buf = Vec::new();
    ciborium::into_writer(value, &mut buf).map_err(|e| Error::Encode(e.to_string()))?;
    Ok(buf)
}

/// Decode a value from CBOR.
pub fn decode<T: DeserializeOwned>(bytes: &[u8]) -> Result<T> {
    ciborium::from_reader(bytes).map_err(|e| Error::Decode(e.to_string()))
}
