//! Wire types. Five messages; resume and initial sync are the same path.
//!
//! Payloads are CBOR. See `docs/decisions.md` for the compatibility rules that
//! keep a log written today readable by a client built in five years.

use serde::{de::DeserializeOwned, Deserialize, Serialize};

use crate::{Error, Id, Result};

/// A position in the server's totally ordered log. The first entry is 1.
pub type Seq = u64;

/// Who authored a mutation. Opaque to Exo; the app decides what it means.
#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct ActorId(String);

impl ActorId {
    pub fn new(id: impl Into<String>) -> Self {
        ActorId(id.into())
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl From<&str> for ActorId {
    fn from(s: &str) -> Self {
        ActorId(s.to_string())
    }
}

impl From<String> for ActorId {
    fn from(s: String) -> Self {
        ActorId(s)
    }
}

impl std::fmt::Display for ActorId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

impl std::fmt::Debug for ActorId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "ActorId({:?})", self.0)
    }
}

/// One mutation, with the identity the log is deduped by.
///
/// `id` is generated by the originating client. The server dedupes on it, which
/// is what makes retrying a push whose response was lost safe without any
/// reasoning at the call site. `seq` is unset until the server assigns one.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Entry<M> {
    pub id: Id,
    pub actor: ActorId,
    #[serde(default)]
    pub seq: Option<Seq>,
    #[serde(rename = "m")]
    pub mutation: M,
}

impl<M> Entry<M> {
    /// A new, unsequenced entry.
    pub fn new(id: Id, actor: ActorId, mutation: M) -> Self {
        Entry {
            id,
            actor,
            seq: None,
            mutation,
        }
    }

    /// The assigned sequence number, or an error if the entry is unsequenced.
    pub fn require_seq(&self) -> Result<Seq> {
        self.seq.ok_or(Error::MissingSeq(self.id))
    }
}

/// Client to server.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "t")]
pub enum ClientMsg<M> {
    /// "I have everything up to `since`; catch me up." Sent on every connect,
    /// whether this is the first sync or the thousandth resume.
    Hello { since: Seq },
    /// Entries authored here, `seq` unset, `id` set.
    Push { entries: Vec<Entry<M>> },
}

/// Server to client.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "t")]
pub enum ServerMsg<M> {
    /// Confirmed entries, in log order. `has_more` means send another `Hello`.
    Batch {
        entries: Vec<Entry<M>>,
        has_more: bool,
    },
    /// These pushed entries are in the log at these sequence numbers.
    /// Parallel arrays: `ids[i]` was assigned `seqs[i]`.
    Ack { ids: Vec<Id>, seqs: Vec<Seq> },
    /// This pushed entry will never be in the log.
    Reject { id: Id, reason: String },
}

/// Encode a value as CBOR.
pub fn encode<T: Serialize>(value: &T) -> Result<Vec<u8>> {
    let mut buf = Vec::new();
    ciborium::into_writer(value, &mut buf).map_err(|e| Error::Encode(e.to_string()))?;
    Ok(buf)
}

/// Decode a value from CBOR.
pub fn decode<T: DeserializeOwned>(bytes: &[u8]) -> Result<T> {
    ciborium::from_reader(bytes).map_err(|e| Error::Decode(e.to_string()))
}
